export const ALL_COLLECTION_ICONS = [
  // --- System / Base ---
  { id: 'instant_mix', label: 'Filter', iconClass: 'icon-filter' },
  { id: 'favorite', label: 'Favorites', iconClass: 'icon-favorite' },
  { id: 'shelves', label: 'Shelves', iconClass: 'icon-shelves' },
  { id: 'shop', label: 'Shop', iconClass: 'icon-shop' },
  { id: 'sold-doll', label: 'Sold', iconClass: 'icon-sold-doll' },
  { id: 'dolls', label: 'Dolls', iconClass: 'icon-dolls' },
  { id: 'eventlog', label: 'Event Log', iconClass: 'icon-eventlog' },
  { id: 'support', label: 'Support', iconClass: 'icon-support' },
  { id: 'settings', label: 'Settings', iconClass: 'icon-settings' },
  { id: 'users', label: 'Users', iconClass: 'icon-users' },
  { id: 'admin_area', label: 'Admin Area', iconClass: 'icon-admin-area' },

  // --- Custom (For new collections) ---
  { id: 'crown', label: 'Crown', iconClass: 'icon-crown' },
  { id: 'diamond', label: 'Diamond', iconClass: 'icon-diamond' },
  { id: 'celebration', label: 'Celebration', iconClass: 'icon-celebration' },
  { id: 'star_shine', label: 'Star Shine', iconClass: 'icon-star-shine' },
  { id: 'heart_smile', label: 'Heart Smile', iconClass: 'icon-heart-smile' },
  { id: 'palette', label: 'Palette', iconClass: 'icon-palette' },
  { id: 'pets', label: 'Pets', iconClass: 'icon-pets' },
  { id: 'style', label: 'Style', iconClass: 'icon-style' },
  { id: 'owl', label: 'Owl', iconClass: 'icon-owl' },
  { id: 'sunny', label: 'Sunny', iconClass: 'icon-sunny' },
  { id: 'rocket', label: 'Rocket', iconClass: 'icon-rocket' },
  { id: 'playground', label: 'Playground', iconClass: 'icon-playground' },
  { id: 'diversity', label: 'Diversity', iconClass: 'icon-diversity' },
  { id: 'lips', label: 'Lips', iconClass: 'icon-lips' },
  { id: 'face_3', label: 'Face Type 3', iconClass: 'icon-face-3' },
  { id: 'face_6', label: 'Face Type 6', iconClass: 'icon-face-6' },
  { id: 'cruelty_free', label: 'Cruelty Free', iconClass: 'icon-cruelty-free' },
  { id: 'deceased', label: 'Deceased', iconClass: 'icon-deceased' },
  { id: 'falling', label: 'Falling', iconClass: 'icon-falling' },
  { id: 'tsunami', label: 'Tsunami', iconClass: 'icon-tsunami' },
  { id: 'man', label: 'Man', iconClass: 'icon-man' },
  { id: 'name', label: 'Name', iconClass: 'icon-name' },
];
